- Numpy is library which handles array

uses of Numpy
============
- Arithmetic operations
- Statistical operations
- Bitwise Operators
- Copying & viewing arrays
- stacking 
- Matrix operations
- Linear Algebra
- Broad casting
- Mathematical operations
- Searching, sorting, & Counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
import sys
sys.version

'3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
#convert list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

`arange()`
- Return evenly spaced values within a given interval.

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(3.0)

array([0., 1., 2.])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20,10) #it gives empty array bcz it must be 1st arg < 2nd arg

array([], dtype=int32)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
#create with variable
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10,10) #similar rows * columns gives empty array

array([], dtype=int32)

In [19]:
np.arange(10,30,5) #here 10 -> start, 30-> stop, 5->step

array([10, 15, 20, 25])

In [20]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In [21]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

`zeros`
- parameter tunning  (inbuild model)
- Hyper parameter tunning (user change inbuild parameter)

In [23]:
#zeros
np.zeros(3) #parameter tunning

array([0., 0., 0.])

In [24]:
np.zeros(5,dtype=int) #Hyper parameter tunning

array([0, 0, 0, 0, 0])

In [25]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [26]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [27]:
zero = np.zeros([2,2])
print(zero)
print('#####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
#####
<class 'numpy.ndarray'>


In [28]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(np.zeros(n,dtype=int)) # hyper parameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [35]:
n

(6, 7)

In [36]:
n1

(6, 8)

In [37]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


- `ones`

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [40]:
np.ones(4)

array([1., 1., 1., 1.])

In [41]:
n

(6, 7)

In [42]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones((5,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [45]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [46]:
np.ones(2)

array([1., 1.])

In [47]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

`range()` 
- returns an object that produces a sequence of integers from start(inclusive) to stop(exclusive) by step.
- range expected at most 3 arguments

In [51]:
range(5)

range(0, 5)

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
r = range(10)
r

range(0, 10)

In [54]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
range(10,40)

range(10, 40)

In [56]:
range(10,40,5)

range(10, 40, 5)

In [57]:
range(10,40,5,1)

TypeError: range expected at most 3 arguments, got 4

In [58]:
r1 = range(10,40,5)
list(range(r1))

TypeError: 'range' object cannot be interpreted as an integer

In [59]:
for i in r1:
    print(i)

10
15
20
25
30
35


In [60]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
list(range(10,40,5))

[10, 15, 20, 25, 30, 35]

In [62]:
list(range(1,10,3))

[1, 4, 7]

In [63]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

- rand : generates random number

In [64]:
rand(3,2)

NameError: name 'rand' is not defined

In [65]:
random.rand(3,2)

NameError: name 'random' is not defined

In [66]:
np.random.rand(5)

array([0.47073621, 0.44015276, 0.18470923, 0.48112834, 0.79396948])

In [67]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [68]:
np.random.rand(2,4) # 2 rows * 2 columns -> its 2d array

array([[0.84611126, 0.47988936, 0.74283374, 0.01968211],
       [0.02669674, 0.11608367, 0.67363031, 0.80618158]])

In [69]:
np.random.randint(2,4)

3

In [70]:
np.random.randint(0,1)

0

In [71]:
np.random.randint(10,20,5) #it generates random number b/w 10 to 19 with specific number i.e 5

array([18, 11, 13, 15, 11])

In [72]:
np.random.randint(1,6,4)

array([4, 1, 4, 4])

In [73]:
np.random.rand(3)

array([0.09424661, 0.40483703, 0.57426159])

In [74]:
np.random.randint(1)

0

In [75]:
np.random.randint(30,20,10)

ValueError: low >= high

In [76]:
np.random.randint(20,30,10)

array([26, 20, 29, 21, 21, 22, 29, 29, 21, 24])

In [77]:
np.random.randint(-30,20,10)

array([-10, -29, -22,   9, -27,   0,   9, -11, -10, -23])

In [78]:
np.random.randint(5,9)

7

In [79]:
np.random.randint(10,21,3)

array([20, 19, 11])

In [80]:
np.random.randint(1,12,10)

array([ 3,  5,  8, 11,  8,  2,  4,  9,  1, 10])

In [81]:
np.random.randint(10,40,(10,10))

array([[28, 34, 34, 34, 19, 10, 30, 34, 10, 11],
       [36, 10, 14, 29, 23, 10, 28, 28, 24, 19],
       [36, 10, 27, 28, 14, 20, 23, 38, 30, 14],
       [26, 17, 18, 15, 15, 19, 29, 33, 11, 20],
       [12, 26, 31, 13, 14, 25, 16, 18, 17, 13],
       [16, 13, 16, 22, 23, 17, 26, 14, 16, 37],
       [30, 26, 31, 12, 15, 10, 33, 36, 12, 10],
       [19, 22, 31, 25, 25, 27, 19, 15, 14, 36],
       [34, 32, 19, 14, 21, 24, 10, 32, 16, 17],
       [24, 34, 33, 26, 20, 25, 33, 12, 35, 22]])

In [82]:
np.random.randint(1,100,(12,12))

array([[76, 52,  9, 50, 25, 59, 29, 61, 64, 24, 71, 96],
       [38, 61, 74, 47, 53, 23, 85, 78, 61, 62, 87, 54],
       [41, 76,  5, 77, 76, 58, 12, 27, 75, 99, 81, 57],
       [14, 47, 30, 97, 11, 90, 57, 94, 31, 70,  6, 29],
       [18, 73, 59, 92, 65, 47, 74, 30, 33, 58, 10, 74],
       [68, 67, 86, 16, 34, 27, 37, 39, 41, 16, 91, 84],
       [92, 27, 70, 30, 88, 55, 18, 33, 96, 21, 39, 76],
       [28, 88, 47, 15, 67, 36, 48, 70, 33, 42, 27,  9],
       [48, 44, 30, 31, 64, 82,  9, 67, 76, 67, 29, 41],
       [61, 35, 69, 54, 64, 57, 47, 98, 48, 70, 84, 47],
       [37, 74,  3, 18, 60, 83, 78, 58, 51, 90,  5, 58],
       [24, 43, 98,  9, 56, 52, 72, 80, 88, 34, 62, 15]])

`reshape`

In [83]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [86]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [87]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [89]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

`slicing in matrix `

In [92]:
b = np.random.randint(10,20,(5,4))  #generate b/w 10 to 20 (5->rows, 4 -> columns)
b

array([[16, 10, 13, 11],
       [19, 15, 10, 10],
       [10, 17, 13, 16],
       [19, 14, 16, 14],
       [13, 13, 15, 19]])

In [93]:
type(b)

numpy.ndarray

In [94]:
b

array([[16, 10, 13, 11],
       [19, 15, 10, 10],
       [10, 17, 13, 16],
       [19, 14, 16, 14],
       [13, 13, 15, 19]])

In [95]:
b[:]  #get all matrix

array([[16, 10, 13, 11],
       [19, 15, 10, 10],
       [10, 17, 13, 16],
       [19, 14, 16, 14],
       [13, 13, 15, 19]])

In [96]:
b[1:3]

array([[19, 15, 10, 10],
       [10, 17, 13, 16]])

In [97]:
b[1,2]

10

In [99]:
b[1:4]

array([[19, 15, 10, 10],
       [10, 17, 13, 16],
       [19, 14, 16, 14]])

In [100]:
b[1,3]

10

In [101]:
b[1,-1]

10

In [102]:
b

array([[16, 10, 13, 11],
       [19, 15, 10, 10],
       [10, 17, 13, 16],
       [19, 14, 16, 14],
       [13, 13, 15, 19]])

In [103]:
b[2:3]

array([[10, 17, 13, 16]])

In [104]:
b[0:-2]

array([[16, 10, 13, 11],
       [19, 15, 10, 10],
       [10, 17, 13, 16]])

In [105]:
b[0,2]

13

In [106]:
b[-5,-3]

10

In [107]:
b[-4,2]

10

`operations`

In [108]:
a = np.random.randint(10,20,10)
a

array([17, 11, 16, 12, 10, 14, 14, 15, 16, 16])

In [109]:
id(a)

3115654586736

In [120]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[39, 20, 90, 61, 78, 70,  7, 57, 61, 52],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [87,  2, 59, 57, 56, 42, 80, 55,  2, 88],
       [10, 14, 17, 85, 46, 65, 97, 99, 33, 55]])

In [115]:
arr

array([0, 1, 2, 3, 4, 5])

In [116]:
arr[:4]

array([0, 1, 2, 3])

In [118]:
arr[:2]

array([0, 1])

In [119]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [121]:
arr2[:]

array([[39, 20, 90, 61, 78, 70,  7, 57, 61, 52],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [87,  2, 59, 57, 56, 42, 80, 55,  2, 88],
       [10, 14, 17, 85, 46, 65, 97, 99, 33, 55]])

In [122]:
arr2[0:5]

array([[39, 20, 90, 61, 78, 70,  7, 57, 61, 52],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50]])

In [123]:
arr2[::-1] #reverse

array([[10, 14, 17, 85, 46, 65, 97, 99, 33, 55],
       [87,  2, 59, 57, 56, 42, 80, 55,  2, 88],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [39, 20, 90, 61, 78, 70,  7, 57, 61, 52]])

In [124]:
arr2[::-2]  #skip 1 row

array([[10, 14, 17, 85, 46, 65, 97, 99, 33, 55],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25]])

In [126]:
arr2[::-3]

array([[10, 14, 17, 85, 46, 65, 97, 99, 33, 55],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [39, 20, 90, 61, 78, 70,  7, 57, 61, 52]])

In [127]:
arr2

array([[39, 20, 90, 61, 78, 70,  7, 57, 61, 52],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [87,  2, 59, 57, 56, 42, 80, 55,  2, 88],
       [10, 14, 17, 85, 46, 65, 97, 99, 33, 55]])

In [128]:
arr2[:-3]

array([[39, 20, 90, 61, 78, 70,  7, 57, 61, 52],
       [ 2, 13, 57, 89, 84, 39, 52, 28, 67, 25],
       [46, 75, 16, 55, 37,  8, 95, 88, 14, 89],
       [60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76]])

In [129]:
arr2[3:]

array([[60, 82, 54,  7, 92, 27, 50, 78, 47, 91],
       [84,  4, 20, 86, 22, 71, 20, 16, 20, 50],
       [80, 67, 22, 53, 69, 98, 87, 38, 55, 47],
       [71, 10, 72, 33, 74, 80, 34, 39, 53, 76],
       [10,  7, 22,  6, 21,  1, 72, 75, 53, 35],
       [87,  2, 59, 57, 56, 42, 80, 55,  2, 88],
       [10, 14, 17, 85, 46, 65, 97, 99, 33, 55]])

In [130]:
arr

array([0, 1, 2, 3, 4, 5])

In [131]:
arr.min()

0

In [132]:
arr.mean()

2.5

In [133]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [134]:
from numpy import *  # *->all
a = array([1,2,3,4,5])
median(a)

3.0

In [135]:
from numpy import *
a = array([0,1,2,3,4,5])
median(a)

2.5

`reshaping`
- it has 3 format
- order - c -> print element using c-type indexing
- order - a -> print arbitrary
- order - f -> print fortran

In [136]:
arr

array([0, 1, 2, 3, 4, 5])

In [137]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [142]:
arr.reshape(2,3,order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
arr.reshape(2,3,order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [144]:
arr.reshape(2,3,order = 'A')

array([[0, 1, 2],
       [3, 4, 5]])

`indexing`

In [147]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
row = 4

In [149]:
col = 5

In [150]:
row

4

In [151]:
col

5

In [152]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
mat[row,col]

45

In [155]:
mat[4,5]

45

In [156]:
mat[6] #print the specific row from the matrix

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

`with slices`

In [159]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
col

5

In [161]:
mat[:,col] # it prints 5th index of column

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [162]:
row

4

In [163]:
mat[row,:] #it prints 4th row

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [164]:
mat[2:6,2:4]  # [2:6] -> row part & [2:4] -> column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [165]:
mat[1:2,2:4]

array([[12, 13]])

In [167]:
mat[2:3,2:3]

array([[22]])

In [168]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

`Masking (or) Filter`

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
id(mat)

3115647826560

In [171]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [172]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [173]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [174]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [175]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])